### ISSUE TITLE
quick question - no storyboards?

### ISSUE THREAD

**Issue by lilayoung** [breadwallet/breadwallet-ios#104]
Hi there, 
I've cloned this repository and it seems there are no storyboards, no @IBOutlets -- i.e. the UI is 100% written in code? If so, that is a feat! Otherwise does that mean the relevant code for the storyboards have been excised from the open-source version?  

I am new to iOS development but am interested in learning and helping the BRD project and crypto in general. 
Just wanted to confirm I've made the right deduction here.  Thank you all and look forward to contributing!

**Comment by ewerx** [comment]
A little late to reply, but yes the UI is written all in code.
