### ISSUE TITLE
Closing app while synchronization is happening causes future app launches to start synchronization at January 2014.  This takes hours!

### ISSUE THREAD

**Issue by JollyGreen** [breadwallet/breadwallet-ios#114]
I've tested this out three or four times now.  I'll let the app spend 2 hours or so to synchronize.  Even after synchronization, it still takes 5 or 10 seconds everytime I open the app to let it synchronize with the latest blocks.  If I close the app during this 5 to 10 second window, the next time the app is launched synchronization will start from January 2014, which takes 2 hours or so.

I've tried deleting the app and re-installing, I've tried deleting the wallets and re-adding, the same issue keeps happening with Bitcoin and Bitcoin Cash wallets.

I have a few transactions from between 1 and 3 years ago, nothing recent, not sure if that affects anything.

iOS 13.2.3, BRD 3.17.3 Build 2

**Comment by ewerx** [comment]
Closing - outdated. Please use support@brd.com for future bug reports.
