### ISSUE TITLE
No such module "BRCrypto"

### ISSUE THREAD

**Issue by maxdenisov** [breadwallet/breadwallet-ios#115]
Hi, 
I am using Pods for SwiftProtobuf.
Issue: No module "BRCrypto"
Any ideas whats is wrong?

**Comment by noaho** [comment]
I had the same problem, turns out I didn't clone the git submodules including breadwallet-core. 

Try running this command in your git folder. 
git submodule update --init --recursive

**Comment by Kuluso** [comment]
before you build this app. you need to build submodules first
