### ISSUE TITLE
What Hierarchical Deterministic BIP does this wallet follow?

### ISSUE THREAD

**Issue by 623637646** [breadwallet/breadwallet-ios#121]
Does it follow BIP 32 or 44 or 49? 
I create an account and checked the address. I can't find which Hierarchical Deterministic BIP this wallet followed.  
Refer to: https://iancoleman.io/bip39/

**Comment by ROSHiix** [comment]
BIP 32 m/0'/0/k

**Comment by 623637646** [comment]
Thanks!
