### ISSUE TITLE
BRD Crashes on IOS after XRP transaction

### ISSUE THREAD

**Issue by jkinum** [breadwallet/breadwallet-ios#123]
BRD wallet crashed after attempting to send XRP.   Won't go past the PIN screen and sometimes crashes on launch now.

Steps:
1. open BRD on IOS 13.3.1
2. Add XRP to wallet
3. copy address into clipboard
4. use address to send XRP to BRD
5. BRD crashes.  Won't reopen.  Crash then repeat and crash again when entering PIN.   

Tried:

1.  reinstall 
2.  reboot

**Comment by acorscadden** [comment]
Thanks for reporting. Could you please make sure you've opted into iOS crash reporting so that the crash shows up in my dashboard?

**Comment by jkinum** [comment]
Share iphone analytics is on, share with app developers is on, share icloud analytics is on.

Also, crashed it a few times for good measure.   There should be something now.
 
----- Original Message -----

**Comment by acorscadden** [comment]
Thank you :) I'll have a look.

**Comment by jkinum** [comment]
Closing this issue.  Resolved after latest application updates are applied.
