### ISSUE TITLE
Update core library to `core-5.0.7` 

### ISSUE THREAD

**Issue by dabitdev** [breadwallet/breadwallet-ios#134]
The wallet is still using `core-4.0.0-beta.2 [Dec 5, 2019]`
The core submodule of the repository is still pointing to the hash bb2024b75d5966971748ab766d48636987de08e8 
https://github.com/breadwallet/breadwallet-core/tree/bb2024b75d5966971748ab766d48636987de08e8

Is there any reason why it has not been updated?

**Comment by ewerx** [comment]
Repo is updated now, was delayed due to some process changes.
