### ISSUE TITLE
Change bitcoin network mining fee

### ISSUE THREAD

**Issue by tanzeelrana** [breadwallet/breadwallet-ios#15]
What do i need to change in the code to change the bitcoin network mining fee ?

TX_FEE_PER_KB ?

**Comment by samuraisam** [comment]
Yes

**Comment by tanzeelrana** [comment]
awesome thanks ! 
I had one more question

the fee_per_kb and . fee_per_kb_econommy is being fetched from the bread wallet api, is it being taken from 21.co ? how is it calculated ? any insight would be helpful 

thanks again for the reply ! :)
