### ISSUE TITLE
fatal: repository 'https://github.com/breadwallet/mobile-font.git/' not found fatal: clone of 'https://github.com/breadwallet/mobile-font.git' into submodule path '/Volumes/My Files/Brd2/Modules/mobile-font' failed Failed to clone 'Modules/mobile-font'. Retry scheduled

### ISSUE THREAD

**Issue by akhilccrb** [breadwallet/breadwallet-ios#154]
fatal: repository 'https://github.com/breadwallet/mobile-font.git/' not found
fatal: clone of 'https://github.com/breadwallet/mobile-font.git' into submodule path '/Volumes/My Files/Brd2/Modules/mobile-font' failed
Failed to clone 'Modules/mobile-font'. Retry scheduled

**Comment by adamdahan** [comment]
Don't forget: 

**Target Integrity**
This copy files build phase contains a reference to a missing file "SwiftProtobuf.framework"

**Package Loading**
Missing package WalletKit.

**Comment by ewerx** [comment]
Fixed in master branch. Reopen if you're still having issues.
