### ISSUE TITLE
Binance Smart Chain support

### ISSUE THREAD

**Issue by nutsplus** [breadwallet/breadwallet-ios#155]
Hello!

I sent my ETH from Binance (Binance Smart Chain (BSC) BEP20) to BRD.

TxID:
https://bscscan.com/tx/0xb6766a4466d4ab6fc130dc9f777aad72731430aea37968551ba7484eadc3b28c

Can you add support BEP20?

**Comment by ewerx** [comment]
BRD does not currently support Binance Smart Chain. Please use support@brd.com for future bug reports and support requests.
