### ISSUE TITLE
iPhone X optimization

### ISSUE THREAD

**Issue by blommegard** [breadwallet/breadwallet-ios#17]
Breadwallet already supports iPhone X, but there are a bunch of layout issues, too small images and the tight coupling of Touch ID == biometrics auth.

**Comment by losh11** [comment]
I'd like to see someone help me with this... I'm going to try doing some of the biometrics assets stuff.

**Comment by losh11** [comment]
I'm going to have a stab at this tomorrow. Although it looks like the breadapp guys have been inactive for a month, so no idea if they will merge my PR.

**Comment by samuraisam** [comment]
We're still around! We only push to this repo on releases now, but would be happy to receive any pull requests!

**Comment by blommegard** [comment]
Is there a specific reason for this @samuraisam, feels hard to contribute on a codebase that is evolving in private?

**Comment by losh11** [comment]
@blommegard created PR #18 to solve this issue.
