### ISSUE TITLE
Missing package product 'WalletKit'

### ISSUE THREAD

**Issue by burhanaras** [breadwallet/breadwallet-ios#172]
Hi,
When building iOS project on XCode 12.4, it gives a build error: 
/Users/.........................../breadwallet-ios/breadwallet.xcodeproj Missing package product 'WalletKit'

How can i add WalletKit to the project? Through SPM or cocoapods?
Thanks for help.

**Comment by ewerx** [comment]
Make sure you follow these steps: https://github.com/breadwallet/breadwallet-ios#development-setup

Specifically `git submodule update --recursive`

**Comment by burhanaras** [comment]
Sorry, tried a few times. But "submodule update --recursive" didn't help.

**Comment by antonshevchenko** [comment]
For me `git submodule update --recursive` didn't do anything, but `git submodule update --init --recursive` did work.

**Comment by infinZero** [comment]
> git submodule update --init --recursive

For me both of the commands `git submodule update --recursive`  and `git submodule update --init --recursive` did not works and giving following result
`fatal: not a git repository (or any of the parent directories): .git`
