### ISSUE TITLE
Private Key

### ISSUE THREAD

**Issue by yannickl** [breadwallet/breadwallet-ios#19]
First of all thank you for your great job! The UI and UX are really great!

I understand you want to keep the app as simple as possible, but it would be great to allow advanced users to import / export their private keys.

I would update the fees and I can't with this wallet. So either you allow the users to update them or allow them to use another wallet to configure the fees if needed.

Best

**Comment by ChuckSRQ** [comment]
Your twelve word seed is the equivalent to your private key. Most wallets can import the seed phrase the same way they can import a priv key.

**Comment by samuraisam** [comment]
You can use the BIP39 phrase to convert to a private key using widely available online tools if this is of interest to you.
