### ISSUE TITLE
Missing code for version 4.10 on AppleStore

### ISSUE THREAD

**Issue by emanuelb** [breadwallet/breadwallet-ios#194]
The version in AppleStore is: 4.10 Updated: Apr 26, 2021
https://apps.apple.com/us/app/id885251393

While the latest version found in this repo is 4.9 from Mar 22, 2021 in latest commit to `master` branch :
https://github.com/breadwallet/breadwallet-ios/commit/f90e2083ee1e908fa5793b8f3d659754166513c2

Please publish the code for latest 4.10 version on AppleStore, and in future ensure that code is published to this repo before it's released to AppleStore.

**Comment by DrewCarlson** [comment]
The latest Android and iOS releases can be found at https://github.com/breadwallet/brd-mobile
