### ISSUE TITLE
When rates fail, tx sending fails

### ISSUE THREAD

**Issue by losh11** [breadwallet/breadwallet-ios#21]
If both rates APIs fail, transaction sending fail. Not only this, transaction information is also hidden from the user + bitcoin balances displayed as 0. It'd be nice if the app could be protected from such an issue. 

There's two points of failure here, and if an ISP/country blocks two domains (api.breadwallet.com | bitpay.com) breadapp will fail to work.

**Comment by samuraisam** [comment]
Yes this is unfortunately a current reality - we are working on figuring out a good solution to this. It was much worse during the Sept '17-Jan '18 run up but we still must stick fee calculation in the middle of sends.

It's a tradeoff between allowing transactions to sometimes be blocked, which is always temporary and recoverable, or always allow transactions to be published, sometimes with irrevocably with fees that are incorrect. Currently we opt for the former. I've file a ticket internally to think about the censorship issue that you bring up - that is a very valid concern.
