### ISSUE TITLE
Comma instead of dot in address box.

### ISSUE THREAD

**Issue by emanuelelaface** [breadwallet/breadwallet-ios#22]
If the Local of the phone is in a country that uses the comma instead of the dot as decimal separator (like Sweden for example), the keypad that appears in Settings->Advanced->Bitcoin Nodes has the comma and the address inserted will be invalid.

By the way I think you should allow to use the name resolution for the server. My node has a different ip if I am at home or if I am abroad because the local dns resolves it differently depending on the network. This is a quite common approach.

**Comment by samuraisam** [comment]
This has been fixed in recent builds.
