### ISSUE TITLE
Support for Electurm Seed Version System

### ISSUE THREAD

**Issue by skyline75489** [breadwallet/breadwallet-ios#23]
It would be great for bread to support the same seed algorithm as Electurm.

Related doc: http://docs.electrum.org/en/latest/seedphrase.html

**Comment by losh11** [comment]
Electrum doesn’t use BIP39, and uses a non-standard seed phrase generation process.

**Comment by samuraisam** [comment]
Our phrase generation is set in stone and is unlikely to change any time soon.
