### ISSUE TITLE
How to get private key?

### ISSUE THREAD

**Issue by nsendhav** [breadwallet/breadwallet-ios#24]
https://github.com/breadwallet/breadwallet-ios/blob/47c17e4ddf12c3db6176e7b1649e31257e454f6b/breadwallet/src/BRCore.swift#L156

In the code I have seen Work-In-Progress for fetching private key. Is it In progress?
or Is it completed?
Please let me know can I use this library code for following:
1. Crating and fetching private key?
2. Can I use the library code for Singapore based wallet app? 
3. Can I buy bitcoin/ethereum in Singapore.
4. Can I use for transaction creation for cryptocurrency?

**Comment by samuraisam** [comment]
We do not currently have plans for exporting your private key. Tools exist to convert the BIP39 phrase to a private key if you require this.
