### ISSUE TITLE
Can I haz SegWit Plz?

### ISSUE THREAD

**Issue by ChuckSRQ** [breadwallet/breadwallet-ios#26]
I am a big fan of Bread Wallet and I really can't thank you guys enough for all the hard work you guys are doing. Love being able to just scan a QR code and press send. 

I would really, really, really, like to be able to use SegWit to avoid paying high fees and to help the network add more capacity.

**Comment by ericallam** [comment]
I second this request. I'd love segwit implemented to be able to reduce transaction fees (and accept segwit outputs).

**Comment by scipio314** [comment]
I'd also like this feature. The fees are way too high to use bitcoin without segwit. 

I recommend this wallet to bitcoin beginners and it's a real buzz kill trying to explain why the bitcoin they have is mostly unusable because of high fees.

**Comment by dlaptev** [comment]
Plus one here. Really like the wallet, but please please add SegWit.

**Comment by bubbapizza** [comment]
Yeah this is a deal breaker.  I wouldn't use breadwallet until it support segwit.

**Comment by johnmbillings** [comment]
I agree - sending from a segway address significantly decreases the transaction fee. Wallet providers who do not implement segwit are hurting the bitcoin ecosystem.

**Comment by papagel** [comment]
Please add segwit support. This is the feature mostly missing from breadwallet.

**Comment by dlaptev** [comment]
@alexanderkustov Just for the record, Samourai wallet is irrelevant to this discussion, because it is not for iOS. But I agree with the message, I would hate to switch to something like GreenAddress.

**Comment by bubbapizza** [comment]
NO

**Comment by samuraisam** [comment]
Segwit is in progress and we are waiting on some network and community developments before we deploy widely.
