### ISSUE TITLE
Custom Fees

### ISSUE THREAD

**Issue by ChuckSRQ** [breadwallet/breadwallet-ios#27]
I like being given two options for fees.  But it would be great to have a middle option or a custom option. Yesterday, I was given the choice between $20 and $1.43.  Big difference.

**Comment by samuraisam** [comment]
We do not currently have plans to offer a custom fee. Our wallet strives to balance the simplicity of physical cash with the power of cryptocurrencies, and a customizable fee settings is not compatible with this vision.
