### ISSUE TITLE
Please consider using this repository for active development

### ISSUE THREAD

**Issue by tt** [breadwallet/breadwallet-ios#30]
I'd like you to reconsider your stance on using this repository as a primary target for active development.

In voisine/breadwallet-ios#98, @voisine said:

> I like to point out that closed source wallets require the same level of trust in the provider as hosted wallets.

In #17, @samuraisam mentioned:

> We only push to this repo on releases now, but would be happy to receive any pull requests!

There are a few issues:

1. A lot of users are running your beta release and have no way to verify what they're running.

2. It appears that you haven't updated this repository; the latest commit, 47c17e4ddf12c3db6176e7b1649e31257e454f6b, is from October 3rd but [the most recent App Store release](https://itunes.apple.com/us/app/bread-bitcoin-wallet/id885251393) was November 20th.

I understand that it makes sense to work on some features in private but I really hope you'll consider using this repository as the target for most changes.

Why do I care? A key reason for why I picked Bread was transparency. From a trust perspective, it's much easier to follow along with incremental changes than every few months when most files in the project have changed. Another argument is being able to contribute pull requests; that's difficult if the source trees diverged significantly.

**Comment by MP0w** [comment]
+1 I wanted to add iPhone X support and discovered this....

**Comment by jfbloom22** [comment]
"A lot of users are running your beta release and have no way to verify what they're running" got me thinking.  Is there really no way for us to verify that someone has not made changes right before doing the iOS build and submitting to Apple?  
I looked around and this is true even for a lot of the hardware wallets.  No way to know if someone modified the firmware before receiving the hardware.  Trezor is an exception to this.  They have instructions on how to verify the firmware matches what is in the open source repo here:  https://github.com/trezor/trezor-mcu/blob/master/README.md

**Comment by MP0w** [comment]
The binary in the store will be signed w/ a certificate so the most simple way I can imagine to verify it is to diff the binary with one archived using the same Xcode version and same commit

**Comment by MIPPL** [comment]
I am working on a fork for an alt-coin and I see that the last version is from Jan 4th (testflight-202) and it does not compile with most recent breadwallet-core library. 

Is there a temptative date to have at least a version compatible with breadwallet-core master commit (40fb26b March 18th as of today) pulled to this repo?

Android version of Breadwallet for example is up to date, tremendous work, congrats!

**Comment by jfbloom22** [comment]
@MP0w sounds like a great idea!  I grabbed the binary with the Apple Configurator app.  https://apple.stackexchange.com/questions/298391/how-do-i-download-an-ios-app-ipa-file-to-my-mac-after-itunes-12-7-update

I slightly modified the instructions from trezor since I am running a Mac and ran: `tail -c +257 BRD\ 2.2.1.ipa | shasum -a 256`
I got: `2ce697c42cff7443ecc27e8ec42335707e89ca46c92f9af4225e79f26346c60c`

I'll test this out on one of my own apps and see if the archived .ipa before I upload to Apple is the same after Apple publishes it and I download it.  I am pretty sure Apple re-signs the apps, so I don't think it will be the same.

**Comment by sneak** [comment]
Regardless of whether or not one verifies binaries from the App Store, everyone with Xcode (no developer account required anymore) can clone the repo, build it themselves, and sideload it onto their own iOS device.  Please keep the repo up to date.

**Comment by samuraisam** [comment]
Yes we still only push with releases but this is much more common now that our internal process is ironed out a bit: once per month, typically the first Tuesday.
