### ISSUE TITLE
Display of historical transactions wrong

### ISSUE THREAD

**Issue by victorengel** [breadwallet/breadwallet-ios#32]
First, the major issue is that historical transactions do not show the amount in bits or BTC. Instead, they show in whatever currency is selected in preferences. Second, the historical amount may include a string such as "Exchange rate when received:" then list an exchange rate. However, the rate listed is not the rate at the time of the transaction. For example, I have a transaction from October 2014 that lists the exchange rate of $16,808.00/btc, which is obviously way off for any time in 2014.

In any case, these errors combined make reconciliation difficult. It seems one must get transaction addresses and look at a blockchain browser to figure out the details. I'm not sure when this broke, but it didn't used to be this way.

**Comment by samuraisam** [comment]
You can change the display by tapping the large currency readout at the top of the transaction list.

I believe the invalid (old) exchange rate bug has been fixed.
