### ISSUE TITLE
About customs fees.

### ISSUE THREAD

**Issue by Rayserzor** [breadwallet/breadwallet-ios#33]
Many wallets even when the mempool is not full calculate the expensive rate to confirm faster but I know that if I pay a cheaper fee I know how long it can take to confirm on the network through network fee comparator bitcoin that shows all the fees from 0 sat/byte to 1000 sat/byte and the maximum confirmation time, I know the risk of putting a fee low too, my transaction will be stuck in mempool for an indeterminate time, but I also know that some algorithms of wallets calculate the fee out of the ordinary, most more expensive than the network asks that is the case of this wallet, add a warning when the user clicks on custoo fee saying that if he places a fee too low then the network asks, your transaction can be stuck indefinitely, that alone is enough, upon reading this warning the risk is the user.

Ideas...

a) add more network fee options, low / low-med / med / med-high / high (at least 5)
b) implement a slider that lets the user select the max time he is willing to wait by estimating the size and using bitcoinfees.earn.com to estimate the times. the slider should have at least 5 steps 1h / 2h / 6h / 12h / 24h
c) let advanced users configure the values for low / med / high priority
d) change the raise network fee option to really raise the fee by a selectable amount or rename it

**Comment by samuraisam** [comment]
We want to balance the simplicity of cash with the power of crypto currencies, and therefore a fully configurable fee setting is not compatible with this vision. We are working to have better and better fee calculation to respond to network conditions and we think the next time we see a big bump our algorithm(s) will respond faster. Thank you for reporting.
