### ISSUE TITLE
Can't sync Bitcoin

### ISSUE THREAD

**Issue by joelklabo** [breadwallet/breadwallet-ios#34]
I keep trying to get up to date with the blockchain but I'm stuck on Oct. 6th, 2013 forever. I'm not sure what else to try.

**Comment by samuraisam** [comment]
Hi Joel, did you ever get this figured out? I imagine one of our recent updates fixed this for you as we have been working on improving syncing.

**Comment by joelklabo** [comment]
Yeah all is well now.
