### ISSUE TITLE
Mnemonic displayed as invalid

### ISSUE THREAD

**Issue by jzakotnik** [breadwallet/breadwallet-ios#35]
I have breadwallet on one iphone and try to restore the same wallet on another iphone (active/active availability ;-). When entering the 12 word mnemonic on the second (identical) breadwallet app, it shows that it is invalid. However it is valid and if I import it in electrum using BIP39, it works out fine.
Any idea what could be wrong here?

**Comment by samuraisam** [comment]
Hi thank you for reporting. This is very unfortunate, but most likely a simple error. Please contact support@brd.com for further assistance.
