### ISSUE TITLE
bread key is 12 chinese charactor in my old phone, but it is Incorrect that use them in my new phone's bread, why ? how to recover my bread ??? 

### ISSUE THREAD

**Issue by jinpengchina** [breadwallet/breadwallet-ios#36]
bread key is 12 chinese charactor in my old phone, but it is Incorrect that use them in my new phone's bread, why ? how to recover my bread ???

because of chinese charator ??? how to recover it in english bread ?

i am very sure my paper key is right.

can the english  bread wallet  recover   the chinese bread wallet ???

**Comment by jinpengchina** [comment]
the paper key of  my chinese  iphone  bread,   i  use the key  at my english s8 phone bread,   it is not work.

then  i delete bread from s8.   and  change my s8 to chinese.
then  i use the paper key at my chinese s8 phone,  it is work. 

the team of bread  support  many language for paper key.    gild the lily

**Comment by samuraisam** [comment]
Please contact support@brd.com
