### ISSUE TITLE
why  i  reinstall bread on my iphone,   the paper key  always is same ???

### ISSUE THREAD

**Issue by jinpengchina** [breadwallet/breadwallet-ios#37]
i delete bread,  and reinstall bread ,   but  the paper key  always is same as old.  why ?

**Comment by amdelamar** [comment]
Start over by going to `Menu` > `Settings` > `Start/Recover Another Wallet` 

FYI it warns you it will wipe your current wallet data if you continue.

**Comment by tanutapi** [comment]
> your backup phrase and pin are stored on the iOS keychain which is maintained even if the app is deleted

[https://github.com/voisine/breadwallet-ios/issues/113](url)
