### ISSUE TITLE
Can't erase wallet without Paper Key

### ISSUE THREAD

**Issue by gubikmic** [breadwallet/breadwallet-ios#38]
I created a wallet recently just to try some things and see how it works. There are no funds. I don't have the paper key anymore. I just want to delete all data and start over but Bread doesn't allow me to continue.

What I find very surprising is that deleting Bread doesn't make any difference. I assumed deleting an app will delete all its data and since iOS 11 not even iCloud keychain items will persist. I didn't look into how Bread persists data but from a user standpoint it's just very frustrating.
I understand that you want to strike a balance between ease of use and security, but right now I just feel extremely patronized by this rigid behavior that doesn't allow me to proceed.

Is there a solution to this?

**Comment by samuraisam** [comment]
You can reset the wallet by going to settings and choosing "start a new wallet."
