### ISSUE TITLE
 idiot bread low fee, user can not change fee, low fee, long waiting, fuck.

### ISSUE THREAD

**Issue by jinpengchina** [breadwallet/breadwallet-ios#40]
over 36 hours,   do not Transfer  6 btc  from bread to other address,      idiot bread low  fee, 
user can not change fee,   low fee,  long waiting,  fuck.
same time , my other transfering btc   is ok  in 10 minutes.  only because of double fee  .

**Comment by jinpengchina** [comment]
60000$,    you said to me only waiting.......

6btc,  your bread  only pay 0.000113 fee  !    user  can not change fee.....

you only can said waiting !!!!!






On Fri, Jan 19, 2018 at 12:46 PM, Bread <support@breadwallet.com> wrote:
##- Please type your reply above this line -##
Hello libai,

Thank you for sending the ID. We understand your concern about the amount of time it is taking for your transaction to confirm. I've taken a look at this transaction and at this point the only option is to wait. The bitcoin network is very busy, and we appreciate your patience as bread doesn't directly control the speed in which transactions are completed. We are looking at improving the fees in the future so there are fewer chances of delays.

Transactions are confirmed by the global bitcoin network, and once a transaction has been sent the only option is to wait for it to be processed. Usually this is done quite quickly, but recently there has been a large increase in network congestion, which is causing some transactions to take many hours longer than usual to be processed.

We understand this situation of intense network congestion is a great inconvenience. Bitcoin is a very new technology, and issues like these are something the bitcoin development community still needs to improve on.

Thank you for your patience and understanding,

Bread Customer Support
breadwallet Support

This email is a service from Bread.
[K66Z4K-EWQ6]

**Comment by jinpengchina** [comment]
over 48 hours,   why my btc  do not come back my wallet !!!!

  6btc,  your bread  only pay 0.000113 fee  !    how idiot  calculation  !!!!

**Comment by samuraisam** [comment]
When there is high contention for block space sometimes there will be delays.
