### ISSUE TITLE
No trusted node fucntion for BCH?

### ISSUE THREAD

**Issue by pinheadmz** [breadwallet/breadwallet-ios#41]
Advanced menu, nodes, manual setting: is this still just for BTC? There's no indication if the manual node should be for BTC or BCH or both or what.

**Comment by samuraisam** [comment]
Yes, this is just for BTC - there is no current demand for having a manual node for BCH now that the cash fork is over. You make a good point though - this should probably be in the "bitcoin" currency settings and not a global advanced setting. 

To answer your question this setting is only for "Bitcoin" and not "Bitcoin Cash"

**Comment by pinheadmz** [comment]
It's not about the fork (for me) it's about trusting full nodes and overcoming the shortcomings of SPV by linking to my own full node. I always appreciated this feature of Bread for BTC.
