### ISSUE TITLE
Bitcoin Cash send dialog shows Bitcoin's USD rate

### ISSUE THREAD

**Issue by teran-mckinney** [breadwallet/breadwallet-ios#43]
I was sending a Bitcoin Cash payment and the bits/USD button worked as expected. 17,000 bits, $12, sure. Close enough. Then pressing send, it says 17,000 bits and $130, clearly using Bitcoin's price and not Bitcoin Cash's price after pressing send from within the first send dialog.

When I sent the transaction, it showed the correct dollar amount in the transactions list.

Let me know if this makes sense. I got it a couple times so hopefully it's not entirely intermittent.

Thanks!

**Comment by samuraisam** [comment]
Yep, thanks for reporting. This has been fixed.
