### ISSUE TITLE
(Sum) when recived isn’t converted to the correct currency 

### ISSUE THREAD

**Issue by benyben27** [breadwallet/breadwallet-ios#49]
If after receiving a transfer you change the currency the “when received” isn’t converted.
For example, if I receive 88.34 ILS(around 25USD) in bitcoin and I change the currency to USD it will display that it used to be 88.34 USD and not ~25 USD.

**Comment by samuraisam** [comment]
Looks like we're storing the currency value but not the currency code - we have an internal ticket for this and will hopefully get to it soon.
