### ISSUE TITLE
Comma vs dot in the 'amount' field in QR codes

### ISSUE THREAD

**Issue by marcocarnut** [breadwallet/breadwallet-ios#50]
We noticed that BreadWallet on iOS with Brazilian Portuguese
as its language fails to correctly parse the "amount" field
in QR codes, resulting in 0 values and forcing the users to
type in the amount manually. If we change the decimal point
to a comma (as it is written in Portuguese), it works correctly.
We believe you should bypass localization to avoid this bug.

**Comment by samuraisam** [comment]
This will be fixed in 3.0.1 which should come out early next week.
