### ISSUE TITLE
Immediate crash on iPhone X + iOS 11.3.1

### ISSUE THREAD

**Issue by jeffreybreen** [breadwallet/breadwallet-ios#52]
Works fine (and looks great!) on iPhone 6 with same OS. Upgraded phones today -- boom -- immediate crash upon launch. Restarting phone doesn't help. Any ideas?

**Comment by akshaynexus** [comment]
I use an iPhone X myself with the latest ios version.No crashes on my phone.A debug log would be helpful for the devs to find the issue.

**Comment by samuraisam** [comment]
Please reach out to support@brd.com - this is something we've seen in a very rare number of cases. They will be able to get you to the next step. Thanks!
