### ISSUE TITLE
Could Not Create Transaction. Nonce too low.

### ISSUE THREAD

**Issue by dcerlanda** [breadwallet/breadwallet-ios#54]
Im having a problem sending Ethereum and any ERC20 token to other wallet or exchanges. I've tried any amount but still the same error. all my transactions have been completed/confirmed no pending. Im using version 2.3 (278) on ios iphone 7 plus.

**Comment by samuraisam** [comment]
Please contact support@brd.com for further help with this issue. We've seen a few of these pop up and usually it's something we can help through support.
