### ISSUE TITLE
feature request: store blockchain data/cache in normal application data store

### ISSUE THREAD

**Issue by sneak** [breadwallet/breadwallet-ios#56]
Every time I get a new phone, I have to resync breadwallet.  I get a new phone several times per year.  It would be really nice if I could have the option to backup my key (if the iOS backup is encrypted, like health data and Google Authenticator data) and also the downloaded blockchain data, so that way when I restore onto a new device, it doesn't take hours to sync and receive my first payment.

**Comment by akshaynexus** [comment]
its best that it resyncs when on a new device.It needs to be up to date

**Comment by samuraisam** [comment]
This is in progress - we are addressing it as part of our warp sync project.
