### ISSUE TITLE
error: "Please select num implementation"

### ISSUE THREAD

**Issue by JIshikawa** [breadwallet/breadwallet-ios#60]
I would make my own app with xcode 9.
But i cannot "Make Project", i become this: error: "Please select num implementation"
Is there someone who knows where this error comes from?
![2018-07-02 11 50 25](https://user-images.githubusercontent.com/19279638/42144917-e3c42842-7df8-11e8-9898-2b09dcc84d85.png)

**Comment by ewerx** [comment]
You will need to pull the submodules in the project:

`git submodule update --init`
