### ISSUE TITLE
Custom fees, please

### ISSUE THREAD

**Issue by keymone** [breadwallet/breadwallet-ios#62]
I get it. Custom fees aren't "friendly". Have a toggle for power users then. Have additional option for high priority transactions. Fee prediction algorithms are never perfect and lead to seriously frustrating situations.

**Comment by brijananand** [comment]
+1 Would be a really handy feature to have. This would provide more control for the users to be able to set a custom fee. The economy option has many a times not provided me low enough fees before during situations where transactions with even lower fees were still being confirmed. 

I understand the idea of maintaining simplicity with just 2 options, but it's always good to provide more control to the users who can turn this feature on or off through the settings page.

**Comment by paintballpanda** [comment]
Biggest letdown of BRD wallet is that it still does not let you set custom fees. The wallet devs have chosen for us that taking anywhere from 45 mins to a few hours before a transaction confirms is what we all want.

**Comment by ewerx** [comment]
Priority fee option was added in 3.13.
