### ISSUE TITLE
Derivation path used for BTC?

### ISSUE THREAD

**Issue by gabmontes** [breadwallet/breadwallet-ios#66]
Can you please confirm what is the derivation path used for BTC wallets in BRD? It looks like the standard `m/44'/0'/0'/change/index` is not being used.

**Comment by leshik** [comment]
The derivation path is `m/0'/0/0`.

**Comment by gabmontes** [comment]
Thanks!

**Comment by 623637646** [comment]
Hi, @leshik , May I know what is the Derivation Path for return transaction change? It doesn't seems to be `m/0'/0/k`.
