### ISSUE TITLE
Translations for Polish 🇵🇱

### ISSUE THREAD

**Issue by michaldev** [breadwallet/breadwallet-ios#76]
_I can't find this project on PhraseApp :/_ 

**Here are translations for iOS app:**

"Buy Bitcoin" -> "Kup Bitcoina"

"Trade" -> "Wymiana"

"Menu" -> "Opcje"

"Scan QR Code" -> "Skanuj kod QR"

"Syncing XXX%" -> "Synchronizowanie XXX%"

"Manage Wallets" -> "Zarządzaj portfelami"

"Preferences" -> "Preferencje"

"Security Settings" -> "Ustawienia Bezpieczeństwa" lub "Bezpieczeństwo"

"Support" -> "Wsparcie"

"Leave us a Review" -> "Napisz nam opinię"

"About" -> "O aplikacji"

"Total Assets" -> "Łącznie posiadasz"

"Send" -> "Wyślij"

"Receive" -> "Otrzymaj"

"Balance" -> "Stan konta"

"sent" -> "wysłane"

"received" -> "otrzymane"

"pending" -> "oczekujące"

"complete" -> "zakończone"

"Your transactions will appear here." -> "Twoje transakcje pojawią się tutaj."

"XX zł per XX" -> "XX zł za XX"

"Cancel" -> "Anuluj"

"Trade Your:" -> "Wymień twoim:"

"Search..." -> "Szukaj..."

"Search" -> "Szukaj"

"History" -> "Historia"

"Loading" -> "Wczytywanie"

"Status" -> "Status"

"Service" -> "Usługa"

"Delivery Date" -> "Data otrzymania"

"Total price paid" -> "Całkowity koszt zakupu"

"Display Currency" -> "Lokalna waluta"

"Bitcoin Settings" -> "Ustawienia Bitcoina"

"Bitcoin Cash Settings" -> "Ustawienia Bitcoin Cash"

"Share Anonymous Data" -> "Wyślij anonimowe dane"

"Reset to Default Currencies" -> "Przywróć domyślne waluty"

"Add Wallets" -> "Dodaj portfele"

"Hide" -> "Ukryj"

"Bitcoin Display Unit" -> "Wyświetlana jednostka bitcoina"

"Exchange Rate" -> "Kurs Wymiany"

"Face ID Spending Limit" -> "Limit przelewów z Face ID"

"Sync Blockchain" -> "Synchronizacja łańcucha"

"When to Sync?" -> "Kiedy zsynchronizować?"

"If a transaction shows as completed on the network but not in your BRD." -> "Jeśli transakcja jest zakończona w sieci, ale niema jej w Twoim portfelu."

"You repeatedly get an error saying your transaction was rejected." -> "Gdy ciągle pojawia się błąd informujący, że transakcja została odrzucona."

"Start Sync" - "Rozpocznij synchronizację"

"You will not be able to send money while syncing with the blockchain." -> "Nie będziesz w stanie wysyłać środków podczas synchronizacji z łańcuchem."

"Redeem Private Key" -> "Wykorzystaj klucz prywatny"

"Import Wallet" -> "Zaimportuj portfel"

"Wallet to be imported" -> "Portfel do zaimportowania"

"Your BRD Wallet" -> "Twór portfel BRD"

"Importing a wallet transfers all the money from other wallet into your BRD wallet using a single transaction." -> "Importowanie portfela przenosi wszystkie pieniądze z innego portfela do portfela BRD za pomocą pojedynczej transakcji."

"Importing a wallet does not include transaction history or other details." -> "Importowanie portfela nie obejmuje historii transakcji ani innych szczegółów."

"Scan Private Key" -> "Skanuj klucz prywatny"

"Share Data?" -> "Udostępnić dane?"

"Help improve BRD by sharing your anonymous data with us. This does not include any financial information. We respect your financial privacy." -> "Pomóż ulepszyć BRD, udostępniając nam anonimowe dane. Nie obejmuje to żadnych informacji finansowych. Szanujemy twoją prywatność."

"Share Anonymous Data?" - "Udostępnić Anonimowe Dane?"

"Update PIN" -> "Zaktualizuj PIN"

"Face ID" -> "Face ID" or "Skanowanie twarzy"

"Paper Key" -> "Papierowy klucz"

"Enter your current PIN" -> "Wprowadź twój aktualny PIN"

"Use your face to unlock your BRD and send money up to a set limit." -> "Użyj swojej twarzy, aby odblokowywać BRD i wysyłać pieniądze bez podawania PINu."

"Enable Face ID for BRD" -> "Włącz Face ID w BRD" or "Włącz skanowanie twarzy w BRD"

"Spending limit:" -> "Limit autoryzacji dla przelewów"

"You can customize your Face ID spending limit from the" -> "Możesz dostosować limit przelewów wykonanych za pomocą Face ID z poziomu:"

"Face ID Spending Limit Screen" -> "ekranu ustawień Face ID"

"Paper Key" - "Papierowy Klucz"

"Your paper key is the only way to restore your BRD if your phone is lost, stolen, broken, or upgraded." -> "Twój papierowy klucz to jedyny sposób na przywrócenie portfelu BRD w przypadku zgubienia, kradzieży, uszkodzenia lub zmiany telefonu."

"We will show you a list of words to write down on a piece of paper and keep safe." -> "Pokażemy ci listę słów, zapisz je na kartce i zachowaj w bezpiecznym miejscu."

"Write Down Paper Key Again" -> "Zapisz ponownie papierowy klucz"

"You last wrote down your paper key on XXX" -> "Ostatnio zapisałeś swój papierowy klucz XXX"

"Privacy Policy" - "Polityka Prywatności"

"Made by the global BRD team." -> "Stworzone przez zespół BRD"

"Unlink from this device" -> "Odłącz od tego urządzenia"

"Bitcoin Nodes" -> "Węzły bitcoina"

"received from" -> "otrzymano od"

"Show Details" -> "Pokaż szczegóły"

"Hide Details" -> "Ukryj szczegóły"

"Total Fee" -> "Całkowita opłata"

"Via" -> "Z"

"Initialized" -> "Zainicjowano"

"Memo -> "Opis"

"Add memo..." -> "Dodaj opis..."

"Transaction ID" -> "ID Transakcji"

"Confirmed in Block" -> "Potwierdzone bloki"

"Not Confirmed" -> "Niepotwierdzone"

"Receiving" -> "Odbieranie"

"receiving via xxx" -> "odbieranie od xxx"

"sending to xxx" -> "wysyłanie do xxx"

"Confirm Trade" -> "Potwierdź wymianę"

"For" -> "Za"

"Price:" -> "Cena:"

"Delivery:" -> "Czas realizacji:"

"Total Charge:" -> "Łączna opłata:"

"Buy" -> "Kup"

"Confirmation" -> "Potwierdzenie"

I don't know:
"Synced through"

**I spent some time on it, please add it in the update.**

_Greetings from Poland ❤_

**Comment by michaldev** [comment]
Is there anyone here?

**Comment by jmacwhyte** [comment]
Hi @michaldev
This is great work, and we really appreciate the effort!

Unfortunately, we do not support Polish localization at this time. Every language we add requires a lot of maintenance (it needs to be added to all of our third party services as well) and at the moment we don't have enough resources to focus on this project. If we do add Polish support in the future, would you be interested in joining our localization platform and help verify the translations?

Thank you for your understanding.

**Comment by michaldev** [comment]
Hi @jmacwhyte
I don’t quite understand. I literally just have done more than half of your work (and it’s up to date). Is copy and paste this hard to do? I thought open source projects are about people working together. I don’t know if I will have enough resources in the future.

Best regards.
