### ISSUE TITLE
How to use breadwallet url scheme

### ISSUE THREAD

**Issue by bug-guide** [breadwallet/breadwallet-ios#77]
(Written as a translator. sorry!)

I want to enter the address and amount specified on the transfer screen.

Can I go directly to the "Send Funds Information" screen via the URL scheme?

 if possible, Please tell me how to configure parameters

This is the screen I want.
![img_c61a98fc6946-1](https://user-images.githubusercontent.com/6512020/47635007-d03c7300-db96-11e8-8307-f0a68002d1d1.jpeg)

**Comment by ewerx** [comment]
`eth://<address>&amount=<amount>&memo=<memo>`
