### ISSUE TITLE
Add Goat Cash (GOAT) and VolAir (VOL) ERC20 Tokens

### ISSUE THREAD

**Issue by krzko** [breadwallet/breadwallet-ios#78]
Hi BRD team,

Just wondering if we can have Goat Cash and VolAir wallets? What do you require?

Here are the details of each token.

Goat Cash (GOAT)
Contract: https://etherscan.io/token/0x9f452e458b024e82d6e3ff50a07b8de74c988523
Decimals: 18
Image: https://cdn.discordapp.com/attachments/482114378779590656/482150420207108096/goatcash-logo512x512.png

VolAir (VOL)
Contract: https://etherscan.io/token/0x33c52ee4bd563a26071619bc6f70146295febe8d
Decimals: 18
Image: https://cdn.discordapp.com/attachments/502222665751330826/502222842784514068/volair-image1024x1024-padding.png

Many thanks.

**Comment by ewerx** [comment]
Please send requests to add tokens to support@brd.com.
