### ISSUE TITLE
Secure Enclave Keys

### ISSUE THREAD

**Issue by ydeveloperios** [breadwallet/breadwallet-ios#81]
In your README, you mention this:

> Private keys are stored only in the secure enclave of the user's phone, inaccessible to anyone other than the user.

Is this true? I thought that the Secure Enclave used secp256**r1** to generate private keys, whereas Bitcoin used secp256**k1** (r vs k). So, I don't understand how it works.

Can you explain in details, how do you use Secure Enclave on iOS?

**Comment by ydeveloperios** [comment]
Thanks for the detailed response! I have two more questions.

1. I’ve searched via Github in your repository for restriction level `kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly` and didn’t find anything. Are you sure about this? If you don't use this restriction level, how does the protection of the private key work and is it secure enough?

2. How is keychain protected if no passcode on the device?

**Comment by ewerx** [comment]
I pasted the wrong enum value, it is `kSecAttrAccessibleWhenUnlockedThisDeviceOnly` which is the same restriction level but this was supported in iOS versions prior to 8.0. The difference is values can still be stored in the keychain with no device passcode, but if this is the case a prompt appears on the home screen warning that the wallet is unprotected until a passcode is set.
