### ISSUE TITLE
Command ExternalBuildToolExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by abrarEpazz** [breadwallet/breadwallet-ios#82]
i am facing this issue and not understand how to fix it please help me to find this issue, i am using latest xcode 10.1

thanks in advance :)

![screenshot 2018-12-03 at 6 06 49 pm](https://user-images.githubusercontent.com/45563780/49445866-b117ad80-f7f4-11e8-9d7f-dac5c90839b0.png)

**Comment by abrarEpazz** [comment]
Hi @voisine Please help me to fix this.

**Comment by ewerx** [comment]
Closing - outdated.
