### ISSUE TITLE
[Feature] Support Monero

### ISSUE THREAD

**Issue by David-Beetle** [breadwallet/breadwallet-ios#95]
**Feature**: Support Monero
**Why?**: Mainly for better privacy.
**Related Links**:
Android: 
https://f-droid.org/en/packages/com.vgorcum.minedmonero/
https://github.com/m2049r/xmrwallet

IOS:
https://github.com/mymonero/mymonero-app-ios

https://www.wikipedia.org/wiki/Monero_(cryptocurrency)
_________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/76336975-feature-support-monero)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=76336975)](https://www.bountysource.com/issues/76336975-feature-support-monero)

**Comment by erickhavel** [comment]
XMR for Android as well please.

Why are so many random coins supported while one of the very few *actually* useful ones (BCH, XMR, ETH/ERC-20) is missing?

**Comment by ewerx** [comment]
We will announce support for new chains through our social media channels or mailing list. See https://brd.com/ for more info.
